{% set name = "zerolancom" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/xinkai-jiang/ZeroLanCom/archive/refs/tags/v{{ version }}.tar.gz
  sha256: <SHA256>

build:
  number: 0
  skip: true  # [windows]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - fmt
    - spdlog
    - zeromq
    - msgpack-c
  run:
    - fmt
    - spdlog
    - zeromq
    - msgpack-c

test:
  commands:
    - test -f $PREFIX/lib/libzerolancom${SHLIB_EXT}  # [unix]
    - test -f $PREFIX/include/zerolancom/zerolancom.hpp  # [unix]

about:
  home: https://github.com/xinkai-jiang/ZeroLanCom
  summary: ZeroLanCom is a lightweight communication framework built on top of ZeroMQ and MessagePack.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xinkai-jiang
